spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306/images}
    username: ${DB_USER:developer}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5000000
